### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by vitich** [SonarQubeCommunity/sonar-erlang#39]
Are there any plans to support Sonar 8.* Enterprise

**Comment by kalidasya** [comment]
hey, I dont think I will have the time to add support. It is usually quite time consuming

**Comment by DaniruKun** [comment]
@vitich  We are working actively on a working fork, it is a bit green right now, but it works on latest LTS. You can star/watch if you are interested: https://github.com/evolution-gaming/sonar-erlang

**Comment by vitich** [comment]
Thanks a lot!
But I need an enterprise edition not community.
Is your plugin compatible with 8.4 enterprise?

--
WBR, vitich@gmail dot com


пт, 18 вер. 2020 о 14:15 Daniils Petrovs <notifications@github.com> пише:

**Comment by DaniruKun** [comment]
Has not been tested with enterprise version, but I don’t see why not. I hope we will publish a release sometime next week.

**Comment by kalidasya** [comment]
@DaniruKun do you want to maintain the project here? I do not plan to do any maintenance anymore, so I would suggest you move your maintenance here (you get rights to the project) or we delete/obsolete this repo and use your repo. Not sure how SonarQube stand nowadays about giving access to this project/group, and how is the upload happens to the marketplace or whatever it is in the app.
wdyt?

**Comment by DaniruKun** [comment]
@kalidasya we would prefer to keep it in our Github org (and it is easier for us since I will not be only maintainer). Afaik having project under `SonarQubeCommunity` is not a pre-requisite for publishing to the Marketplace. It's not an immediate item on our agenda, but I will push for it to be done in the next quarter.
We don't want to rush things yet, when there is better documentation available and a working built release, we will let everyone know, hope this helps 🙂

**Comment by kalidasya** [comment]
@DaniruKun makes sense, just ping me here in an issue when you are ready and I will update the readme or delete this project, you clone has the history of this project right? then I guess I will just ask for deletion
